Fix `matchLabelKeys` example yaml syntax
It should be `spec.template.spec.affinity` instead of `spec.template.affinity`.

```
$ explain deploy.spec.template.spec.affinity
GROUP:      apps
KIND:       Deployment
VERSION:    v1

FIELD: affinity <Affinity>

...
```
```
$ k explain deploy.spec.template.affinity
GROUP:      apps
KIND:       Deployment
VERSION:    v1

error: field "affinity" does not exist
```