Update kustomization.md
command: ["start", "--host", "\$(MY_SERVICE_NAME)"]
The back slash causes an error. So removed it.
The error detail below
```
Error: rawResources failed to read Resources: YAML file [deployment.yaml] encounters a format error.
error converting YAML to JSON: yaml: line 18: found unknown escape character
```
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```