Fix ordered list with nested unordered list items
Adding Kubernetes Kubeadm + Digital Rebar integration for On-Prem installs (#10118)

* add Digital Rebar KRIB to installer lists

* second review, minor cleanups

* address corrections flagged by @neolit123

* resolve merge - fix table

* add Digital Rebar KRIB to installer lists

* second review, minor cleanups

* address corrections flagged by @neolit123

tasks-with-cron-jobs: explain the steps expression (#10540)

The `/` steps expression is used throughout this doc but is never explained. Worse, it isn't actually part of the "normal" Cron spec linked in Wikipedia and is an extension added to vixiecron

Blog Post: Network bootable servers farm with LTSP (some fixes) (#10466)

* upd: small changes, bump docker version

* Update 2018-10-02-network-bootable-farm-with-ltsp.md

* add: why not coreos

* add: why not coreos

fix glossary entry for quantity (#10653)

Show clusterIP in Services diagrams instead of ServiceIP (#10663)

* Use clusterIP instead of ServiceIP in graphs and documentation

Using ServiceIP instead of clusterIP in images can be confusing when
they're showing the clusterIP.

Since the SVGs are updated, the "Note" is now redundant.

* Update out-dated service diagram PNGs

Bug in coredns ConfigMap spec (#10585)

Missing the `data` label in configmap spec.  Attempting to create the file as is results in:
```
error: error validating "STDIN": error validating data: ValidationError(ConfigMap): unknown field "Corefile" in io.k8s.api.core.v1.ConfigMap; if you choose to ignore these errors, turn validation off with --validate=false
```

fix the output for rolling back a deployment (#10597)

Blog Post: Tips first KubeCon Presentation (Pt. 1) (#10509)

* Blog Post: Tips first KubeCon Presentation (Pt. 1)

Part 1 about experiences from my first KubeCon presentation.
Pre-review and collaboration with @kbarnard10 @parispittman.

* Update Tips-For-First-KubeCon-Presentation-Part-1.MD

* Update and rename Tips-For-First-KubeCon-Presentation-Part-1.MD to 2018-10-18-tips-for-first-kubecon-presentation-part-1.md

update sass again