Add quotes to JSONPATH bash variable
The command was failing with

    error: error parsing jsonpath {range, unclosed action

We need to quote `$JSONPATH` so the full contents of the variable are
passed to `-o jsonpath=`.

Fixes #4258