update the gcloud command example since
It doesn't accept assigning a value.

[13:48:57] $ gcloud container clusters create test-single2   --zone=us-central1-b --enable-autoscaling=true --min-nodes=1 --max-nodes=9 --num-nodes=1 
usage: gcloud container clusters create  NAME [optional flags]
ERROR: (gcloud.container.clusters.create) argument --enable-autoscaling: ignored explicit argument 'true'