Remove 'expirationSeconds' from csr heredoc
Just running through the csr example and threw the error:

```
error: error validating "STDIN": error validating data: ValidationError(CertificateSigningRequest.spec): unknown field "expirationSeconds" in io.k8s.api.certificates.v1.CertificateSigningRequestSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

Removed it.  I used kubectl explain to see if it is somewhere else now, but it does not appear to be in either metadata or spec, although I did not search exhaustively.  In any event this can at least kick off whatever the correct change needs to be.