Update kubectl explain usage case (#19612)
You can't specify more then one resources at one for explain. See error below:
$ kubectl explain pods,svc
the server doesn't have a resource type "pods,svc"

error: We accept only this format: explain RESOURCE