Fix tiny typo in NFS Volume example.
`Pod.spec.volumes.nfs.readOnly` was subtly misspelled `readonly`, which was breaking the example.

```
$ k explain Pod.spec.volumes.nfs.readonly
error: field "readonly" does not exist
$ k explain Pod.spec.volumes.nfs.readOnly
KIND:     Pod
VERSION:  v1

FIELD:    readOnly <boolean>
...
```