Bug in coredns ConfigMap spec
Missing the `data` label in configmap spec.  Attempting to create the file as is results in:
```
error: error validating "STDIN": error validating data: ValidationError(ConfigMap): unknown field "Corefile" in io.k8s.api.core.v1.ConfigMap; if you choose to ignore these errors, turn validation off with --validate=false
```