Update missing kubever on weave network
```
$ export kubever=$(kubectl version | base64 | tr -d '
> ')
$ kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version="
error: unable to read URL "https://cloud.weave.works/k8s/net?k8s-version=", server reported 400 Bad Request, status code=400
```
```
$ kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"
serviceaccount "weave-net" created
clusterrole.rbac.authorization.k8s.io "weave-net" created
clusterrolebinding.rbac.authorization.k8s.io "weave-net" created
role.rbac.authorization.k8s.io "weave-net" created
rolebinding.rbac.authorization.k8s.io "weave-net" created
daemonset.extensions "weave-net" created
```